#    snapcraft yaml for endless-sky.
#    Copyright (C) 2021-2022 joker2770
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: endlesssky
version: '0.9.14' # just for humans, typically '1.2+git' or '1.3.2'
summary: Endless Sky is a sandbox-style space exploration game. # 79 char long summary
description: |
  Endless Sky starts off the player with a decision to pick their own ship
  based on their style of gameplay. Will you choose to be the merchant and
  enjoy quiet and steady work among the stars? Or will you become a bounty
  hunter and fight off pirates to strike it rich? You may even decide to
  become the bad guy and choose to be the pirate yourself.

  _More build details: https://github.com/Joker2770/endlesssky-snap_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

layout:
  /usr/local/share/games/endless-sky:
    bind: $SNAP/usr/local/share/games/endless-sky
  /usr/local/share/icons:
    bind: $SNAP/usr/local/share/icons
  /usr/local/share/man:
    bind: $SNAP/usr/local/share/man
  /usr/local/share/metainfo:
    bind: $SNAP/usr/local/share/metainfo

apps:
  endlesssky:
    command: usr/local/games/endless-sky
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - audio-playback
      - removable-media
      - network
      - network-bind

parts:
  endlesssky:
    plugin: scons
    source: "https://github.com/endless-sky/endless-sky.git"
    source-depth: 1
    source-branch: master
    source-type: git
    build-packages:
      - gcc
      - g++
      - scons
      - python3
      - python3-pip
      - libsdl2-dev
      - libpng-dev
      - libjpeg-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libopenal-dev
      - libmad0-dev
      - uuid-dev
    stage-packages:
      - libsdl2-2.0-0
      - libpng16-16
      - libjpeg9
      - libgl1
      - libglew2.0
      - libopenal1
      - libmad0
      - uuid
    override-build: |
      sudo pip3 install scons
      scons
      sudo scons install
