#    snapcraft yaml for endless-sky.
#    Copyright (C) 2021-2024 joker2770
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: endlesssky
version: '0.10.10' # just for humans, typically '1.2+git' or '1.3.2'
summary: Endless Sky is a sandbox-style space exploration game. # 79 char long summary
description: |
  Endless Sky starts off the player with a decision to pick their own ship
  based on their style of gameplay. Will you choose to be the merchant and
  enjoy quiet and steady work among the stars? Or will you become a bounty
  hunter and fight off pirates to strike it rich? You may even decide to
  become the bad guy and choose to be the pirate yourself.

  **more options could found as follow command**

     endlesssky.endlesssky-pure --help

  _More build details: https://github.com/Joker2770/endlesssky-snap_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core22

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/local/share/games:
    bind: $SNAP/usr/local/share/games
  /usr/local/share/icons:
    bind: $SNAP/usr/local/share/icons
  /usr/local/share/doc:
    bind: $SNAP/usr/local/share/doc
  /usr/local/share/man:
    bind: $SNAP/usr/local/share/man
  /usr/local/share/metainfo:
    bind: $SNAP/usr/local/share/metainfo
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0/modules:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0/modules

apps:
  endlesssky-pure:
    command: usr/local/games/endless-sky
    command-chain: ["bin/desktop-launch"]
    common-id: io.github.endless_sky.endless_pure
    environment:
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/local/lib"
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - alsa
      - audio-playback
      - removable-media
      - gsettings
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - system-trace
      - network
      - network-bind
  endlesssky:
    command: "usr/local/games/endless-sky -r $SNAP/usr/local/share/games/endless-sky/"
    command-chain: ["bin/desktop-launch"]
    common-id: io.github.endless_sky.endless_sky
    environment:
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/local/lib"
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - alsa
      - audio-playback
      - removable-media
      - gsettings
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - system-trace
      - network
      - network-bind

parts:
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
  endlesssky:
    after: [desktop-glib-only]
    plugin: cmake
    cmake-parameters:
      - "-DES_USE_VCPKG=OFF"
      - "-DCMAKE_INSTALL_PREFIX=/usr/local"
      - "-DCMAKE_BUILD_TYPE=Release"
    source: "https://github.com/endless-sky/endless-sky.git"
    source-depth: 1
    source-branch: master
    source-type: git
    build-packages:
      - gcc
      - g++
      - make
      - catch2
      - libsdl2-dev
      - libpng-dev
      - libjpeg-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libopenal-dev
      - libmad0-dev
    stage-packages:
      - libsdl2-2.0-0
      - libpng16-16
      - libjpeg8
      - libgl1
      - libglew2.2
      - libopenal1
      - libopengl0
      - libmad0
